"""Quadlet renderer (v2/M2): exact-text snapshots for every variant, path
layout, the spec-hash marker round-trip, and proof that injection cannot
reach unit text (the spec grammar rejects it at construction)."""

from __future__ import annotations

import pytest

from app.domain.specs import EndpointSpec, ServiceSpec, StackSpec, VolumeSpec, spec_hash
from app.domain.validate import SpecValidationError
from app.system import quadlet
from app.system.tenants import InvalidTenantUserError


def full_stack() -> StackSpec:
    return StackSpec(
        name="blog",
        tenant="hosty-t-7",
        services=(
            ServiceSpec(
                name="web",
                image="docker.io/library/nginx:1.27@sha256:" + "a" * 64,
                env=(("APP_ENV", "prod"), ("WP_HOME", "https://blog.example.com")),
                internal_port=80,
                host_port=20001,
                memory_mb=512,
                cpu_percent=150,
                is_web=True,
            ),
            ServiceSpec(name="db", image="docker.io/library/mariadb:11"),
        ),
        volumes=(
            VolumeSpec(name="content", service="web", mount_path="/var/www/html"),
            VolumeSpec(name="dbdata", service="db", mount_path="/var/lib/mysql"),
        ),
        endpoints=(EndpointSpec(domain="blog.example.com", service="web"),),
    )


def test_container_unit_snapshot_full():
    stack = full_stack()
    web = stack.services[0]
    assert quadlet.container_unit(stack, web) == (
        "# hosty-managed — generated by the panel; manual edits are overwritten\n"
        "# hosty-stack=blog\n"
        "# hosty-service=web\n"
        f"# hosty-spec-hash={spec_hash(stack, web)}\n"
        "\n"
        "[Unit]\n"
        "Description=hosty stack blog — service web\n"
        "\n"
        "[Container]\n"
        "ContainerName=blog-web\n"
        "Image=docker.io/library/nginx:1.27@sha256:" + "a" * 64 + "\n"
        "Network=blog.network\n"
        "NoNewPrivileges=true\n"
        "LogDriver=journald\n"
        "Label=hosty.stack=blog\n"
        "Label=hosty.managed=1\n"
        "PublishPort=127.0.0.1:20001:80\n"
        "EnvironmentFile=/home/hosty-t-7/stacks/blog/env/web.env\n"
        "Volume=/home/hosty-t-7/stacks/blog/volumes/content:/var/www/html\n"
        "PodmanArgs=--memory=512m --cpus=1.5\n"
        "\n"
        "[Service]\n"
        "Restart=always\n"
        "TimeoutStartSec=300\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def test_container_unit_snapshot_minimal():
    """No port, no env, no volumes, no limits — hardening lines remain."""
    stack = full_stack()
    db = stack.services[1]
    assert quadlet.container_unit(stack, db) == (
        "# hosty-managed — generated by the panel; manual edits are overwritten\n"
        "# hosty-stack=blog\n"
        "# hosty-service=db\n"
        f"# hosty-spec-hash={spec_hash(stack, db)}\n"
        "\n"
        "[Unit]\n"
        "Description=hosty stack blog — service db\n"
        "\n"
        "[Container]\n"
        "ContainerName=blog-db\n"
        "Image=docker.io/library/mariadb:11\n"
        "Network=blog.network\n"
        "NoNewPrivileges=true\n"
        "LogDriver=journald\n"
        "Label=hosty.stack=blog\n"
        "Label=hosty.managed=1\n"
        "Volume=/home/hosty-t-7/stacks/blog/volumes/dbdata:/var/lib/mysql\n"
        "\n"
        "[Service]\n"
        "Restart=always\n"
        "TimeoutStartSec=300\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def test_network_unit_snapshot():
    assert quadlet.network_unit(full_stack()) == (
        "# hosty-managed — generated by the panel; manual edits are overwritten\n"
        "# hosty-stack=blog\n"
        "\n"
        "[Network]\n"
        "NetworkName=hosty-blog\n"
        "Label=hosty.stack=blog\n"
        "Label=hosty.managed=1\n"
    )


def test_unit_files_is_the_complete_set():
    files = quadlet.unit_files(full_stack())
    assert sorted(files) == ["blog-db.container", "blog-web.container", "blog.network"]


def test_env_files_only_for_services_with_env():
    env_files = quadlet.env_files(full_stack())
    assert list(env_files) == ["/home/hosty-t-7/stacks/blog/env/web.env"]
    assert env_files["/home/hosty-t-7/stacks/blog/env/web.env"] == (
        "APP_ENV=prod\nWP_HOME=https://blog.example.com\n"
    )


def test_spec_hash_marker_round_trips():
    stack = full_stack()
    web = stack.services[0]
    assert quadlet.read_spec_hash(quadlet.container_unit(stack, web)) == spec_hash(stack, web)


def test_ownership_markers_round_trip():
    stack = full_stack()
    text = quadlet.container_unit(stack, stack.services[0])
    assert quadlet.read_stack_marker(text) == "blog"
    assert quadlet.read_service_marker(text) == "web"
    assert quadlet.read_stack_marker(quadlet.network_unit(stack)) == "blog"
    assert quadlet.read_service_marker(quadlet.network_unit(stack)) is None
    assert quadlet.read_stack_marker("garbage") is None
    assert quadlet.read_stack_marker(None) is None


@pytest.mark.parametrize(
    "garbage",
    ["", "[Container]\nImage=x\n", "# hosty-spec-hash=NOT-HEX\n", "# hosty-spec-hash=abc\n", None],
)
def test_read_spec_hash_is_total(garbage):
    assert quadlet.read_spec_hash(garbage) is None


def test_paths():
    assert quadlet.unit_dir(5001) == "/etc/containers/systemd/users/5001"
    assert quadlet.volume_host_dir("hosty-t-7", "blog", "content") == (
        "/home/hosty-t-7/stacks/blog/volumes/content"
    )
    assert quadlet.env_file_path("hosty-t-7", "blog", "web") == (
        "/home/hosty-t-7/stacks/blog/env/web.env"
    )
    assert quadlet.service_unit_name("blog", "web") == "blog-web.service"


@pytest.mark.parametrize("uid", [0, -1, True, "5001", None])
def test_unit_dir_rejects_bad_uids(uid):
    with pytest.raises(ValueError):
        quadlet.unit_dir(uid)


def test_path_helpers_reject_non_tenant_users():
    with pytest.raises(InvalidTenantUserError):
        quadlet.volume_host_dir("root", "blog", "content")


def test_injection_cannot_reach_unit_text():
    """The renderer only accepts validated specs; every injection attempt
    dies at spec construction, so no escaping logic exists to get wrong."""
    with pytest.raises(SpecValidationError):
        ServiceSpec(name="web", image="-rm -rf /")  # leading dash
    with pytest.raises(SpecValidationError):
        ServiceSpec(name="web", image="nginx", env=(("EVIL", "a\n[Service]\nExecStart=sh"),))
    with pytest.raises(SpecValidationError):
        VolumeSpec(name="data", service="web", mount_path="/data:/etc")  # `:` split
    with pytest.raises(SpecValidationError):
        VolumeSpec(name="data", service="web", mount_path="/data/../../etc")
    with pytest.raises(SpecValidationError):
        StackSpec(name="blog\n", tenant="hosty-t-7", services=(ServiceSpec("web", "nginx"),))
