"""Executor service-control behaviour (v2/M3, ADR-013).

Covers `_control_service`'s handling of systemd's "Unit ... not found" —
the failure mode behind the production `start mongodb-6eru-db.service ...
Unit not found` incident, which the FakeHost-backed orchestration suite
cannot express (it fakes systemd wholesale).

A freshly lingered tenant user manager races the first daemon-reload, so a
just-written quadlet unit can be momentarily absent; the executor re-runs
the generator and retries. A unit still missing after the bounded retries is
a real host fault and gets an actionable message. Genuine start failures
(image pull, crash loop) must pass through untouched, with no retries.
"""

from __future__ import annotations

import pytest

from app.core.config import Settings
from app.db.models import Tenant, User
from app.domain import actions as act
from app.orchestration import executor
from app.system import systemd_user as systemd_user_mod


@pytest.fixture
async def db(app):
    async with app.state.sessionmaker() as session:
        yield session


async def _ctx(db, settings) -> executor.ExecContext:
    db.add(User(id=1, username="u1", password_hash="x", role="client"))
    await db.commit()
    db.add(
        Tenant(
            user_id=1, linux_user="hosty-t-1", uid=6001, subuid_start=1_000_000, subuid_count=65536
        )
    )
    await db.commit()

    async def sync_caddy() -> None:  # pragma: no cover - unused here
        return None

    async def tenant_in_use(_t: str) -> bool:  # pragma: no cover - unused here
        return True

    return executor.ExecContext(
        db=db, settings=settings, sync_caddy=sync_caddy, tenant_in_use=tenant_in_use
    )


@pytest.fixture
def fast_retries(monkeypatch):
    """Drop the inter-retry backoff so race-recovery tests don't sleep, and
    count daemon-reloads (each retry must re-run the quadlet generator)."""
    monkeypatch.setattr(executor, "_REGENERATE_RETRY_DELAYS", (0, 0, 0, 0))
    reloads = {"count": 0}

    async def daemon_reload(user):
        reloads["count"] += 1

    monkeypatch.setattr(systemd_user_mod, "daemon_reload", daemon_reload)
    return reloads


async def test_persistent_unit_not_found_is_translated_after_retries(
    db, settings: Settings, monkeypatch, fast_retries
):
    ctx = await _ctx(db, settings)
    attempts = {"count": 0}

    async def control(user, action, unit):
        attempts["count"] += 1
        raise systemd_user_mod.SystemdUserError(
            f"start {unit} for {user} failed: Failed to start {unit}: Unit {unit} not found."
        )

    monkeypatch.setattr(systemd_user_mod, "control", control)

    with pytest.raises(executor.ExecutorError) as excinfo:
        await executor.execute(act.StartService("hosty-t-1", "mongodb-6eru", "db"), ctx)

    message = str(excinfo.value)
    assert "was not generated by the podman quadlet user-generator" in message
    assert (
        "/etc/containers/systemd/users/6001" in message
    )  # the real unit dir, resolved from the ledger
    assert "podman >= 4.6" in message
    assert "Unit mongodb-6eru-db.service not found" in message  # original preserved
    # 1 initial start + 4 retries, each retry preceded by a regenerating reload.
    assert attempts["count"] == 5
    assert fast_retries["count"] == 4


async def test_unit_appears_after_a_reload_and_start_succeeds(
    db, settings: Settings, monkeypatch, fast_retries
):
    """The freshly-lingered-manager race: the unit is missing on the first
    attempt but materializes after a regenerating reload — the start then
    succeeds, no error surfaces."""
    ctx = await _ctx(db, settings)
    attempts = {"count": 0}

    async def control(user, action, unit):
        attempts["count"] += 1
        if attempts["count"] < 3:  # missing for the first two tries, then generated
            raise systemd_user_mod.SystemdUserError(
                f"Failed to start {unit}: Unit {unit} not found."
            )

    monkeypatch.setattr(systemd_user_mod, "control", control)

    await executor.execute(act.StartService("hosty-t-1", "mongodb-6eru", "db"), ctx)  # no raise
    assert attempts["count"] == 3
    assert fast_retries["count"] == 2  # one reload before each of the two retries


async def test_genuine_start_failure_passes_through_unchanged(
    db, settings: Settings, monkeypatch, fast_retries
):
    ctx = await _ctx(db, settings)

    async def control(user, action, unit):
        raise systemd_user_mod.SystemdUserError(
            "Job for mongodb-6eru-db.service failed: image pull error"
        )

    monkeypatch.setattr(systemd_user_mod, "control", control)

    # Not a "not found"/"not loaded" failure → surfaced verbatim, no retries.
    with pytest.raises(systemd_user_mod.SystemdUserError) as excinfo:
        await executor.execute(act.StartService("hosty-t-1", "mongodb-6eru", "db"), ctx)
    assert "image pull error" in str(excinfo.value)
    assert "was not generated" not in str(excinfo.value)
    assert fast_retries["count"] == 0  # genuine failures must not trigger regeneration


async def test_restart_not_loaded_failure_is_also_translated(
    db, settings: Settings, monkeypatch, fast_retries
):
    ctx = await _ctx(db, settings)

    async def control(user, action, unit):
        assert action == "restart"
        raise systemd_user_mod.SystemdUserError(f"Unit {unit} not loaded.")

    monkeypatch.setattr(systemd_user_mod, "control", control)

    with pytest.raises(executor.ExecutorError) as excinfo:
        await executor.execute(act.RestartService("hosty-t-1", "mongodb-6eru", "db"), ctx)
    assert "was not generated by the podman quadlet user-generator" in str(excinfo.value)
