"""Dynamic compose blueprints: data-driven one-click templates with Hosty
metadata and Coolify-style variable defaults/required markers."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from app.domain.validate import SpecValidationError
from app.orchestration.blueprints.base import Allocation
from app.orchestration.blueprints.compose import ComposeBlueprint


def write_template(tmp_path, text: str):
    path = tmp_path / "postgres.yml"
    path.write_text(text, encoding="utf-8")
    return path


def test_builtin_template_images_are_fully_qualified_and_digest_pinned():
    templates_dir = Path(__file__).resolve().parent.parent / "templates"
    image_refs: list[tuple[str, str, str]] = []
    for path in sorted(templates_dir.glob("*.yml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        services = data.get("services", {}) if isinstance(data, dict) else {}
        for service_name, service in services.items():
            if isinstance(service, dict) and service.get("image"):
                image_refs.append((path.name, str(service_name), str(service["image"])))

    assert image_refs
    for template, service, image in image_refs:
        assert image.startswith("docker.io/"), f"{template}:{service} uses unqualified {image}"
        assert "@sha256:" in image, f"{template}:{service} is not digest pinned"


def test_compose_blueprint_metadata_drives_json_schema_title(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
x-hosty:
  name: "PostgreSQL"
  version: 3
  category: "Databases"
  icon: "postgres"
  description: "Deploy Postgres"
  inputs:
    version:
      type: "string"
      default: "16"
services:
  db:
    image: postgres:${version}
""",
        )
    )

    assert blueprint.id == "postgres"
    assert blueprint.display_name == "PostgreSQL"
    assert blueprint.category == "Databases"
    assert blueprint.inputs().model_json_schema()["title"] == "PostgreSQL"


def test_compose_blueprint_renders_services_ports_env_and_volumes(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
x-hosty:
  name: "PostgreSQL"
  ports: [db]
  secrets: [db_password]
  inputs:
    version:
      type: "string"
      default: "16"
    database:
      type: "string"
      default: "postgres"
    user:
      type: "string"
      default: "postgres"
services:
  db:
    image: postgres:${version:-16}
    ports:
      - 127.0.0.1:5432:5432/tcp
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${db_password:?generated by Hosty}
      POSTGRES_INITDB_ARGS: 123
    volumes:
      - db-data:/var/lib/postgresql/data
""",
        )
    )
    inputs = blueprint.inputs().model_validate({"version": "16", "database": "app", "user": "app"})
    spec = blueprint.render(
        "pg",
        inputs,
        Allocation(tenant="hosty-t-7", ports={"db": 20100}, secrets={"db_password": "secret"}),
    )

    assert spec.services[0].image == "docker.io/library/postgres:16"
    assert spec.services[0].internal_port == 5432
    assert spec.services[0].host_port == 20100
    assert dict(spec.services[0].env) == {
        "POSTGRES_DB": "app",
        "POSTGRES_INITDB_ARGS": "123",
        "POSTGRES_PASSWORD": "secret",
        "POSTGRES_USER": "app",
    }
    assert spec.volumes[0].name == "db-data"
    assert spec.volumes[0].mount_path == "/var/lib/postgresql/data"


def test_compose_blueprint_strips_short_volume_access_mode(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
services:
  app:
    image: nginx:1.27
    volumes:
      - content:/usr/share/nginx/html:ro
""",
        )
    )
    spec = blueprint.render(
        "app", blueprint.inputs().model_validate({}), Allocation(tenant="hosty-t-7")
    )
    assert spec.volumes[0].mount_path == "/usr/share/nginx/html"


@pytest.mark.parametrize("text", ["", "[]", "services: {}", "services:\n  app: broken"])
def test_compose_blueprint_rejects_malformed_structure(tmp_path, text):
    with pytest.raises(SpecValidationError):
        ComposeBlueprint(write_template(tmp_path, text))


def test_compose_blueprint_rejects_unsupported_local_build_without_image(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
""",
        )
    )
    with pytest.raises(SpecValidationError, match="local build context"):
        blueprint.render(
            "app", blueprint.inputs().model_validate({}), Allocation(tenant="hosty-t-7")
        )


def test_compose_blueprint_rejects_missing_required_variable(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
x-hosty:
  name: "Required"
services:
  app:
    image: ghcr.io/example/app:${missing:?}
""",
        )
    )

    with pytest.raises(SpecValidationError, match="missing"):
        blueprint.render(
            "app",
            blueprint.inputs().model_validate({}),
            Allocation(tenant="hosty-t-7", ports={}, secrets={}),
        )


def test_compose_blueprint_renders_git_web_endpoint(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
x-hosty:
  name: "Git Repository"
  ports: [web]
  web: web
  domain_input: domain
  inputs:
    repo:
      type: string
    branch:
      type: string
      default: main
    internal_port:
      type: integer
      default: 3000
    domain:
      type: string
services:
  web:
    build: ${repo}#${branch}
    ports:
      - "${internal_port}:${internal_port}"
""",
        )
    )
    inputs = blueprint.inputs().model_validate(
        {
            "repo": "https://github.com/example/app.git",
            "branch": "main",
            "internal_port": 3000,
            "domain": "app.example.com",
        }
    )
    spec = blueprint.render(
        "app",
        inputs,
        Allocation(tenant="hosty-t-7", ports={"web": 20100}),
    )

    service = spec.services[0]
    assert service.build_repo == "https://github.com/example/app.git"
    assert service.build_branch == "main"
    assert service.internal_port == 3000
    assert service.host_port == 20100
    assert service.is_web is True
    assert spec.endpoints[0].domain == "app.example.com"
