"""Dynamic compose blueprints: data-driven one-click templates with Hosty
metadata and Coolify-style variable defaults/required markers."""

from __future__ import annotations

import pytest

from app.domain.validate import SpecValidationError
from app.orchestration.blueprints.base import Allocation
from app.orchestration.blueprints.compose import ComposeBlueprint


def write_template(tmp_path, text: str):
    path = tmp_path / "postgres.yml"
    path.write_text(text, encoding="utf-8")
    return path


def test_compose_blueprint_metadata_drives_json_schema_title(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
x-hosty:
  name: "PostgreSQL"
  version: 3
  category: "Databases"
  icon: "postgres"
  description: "Deploy Postgres"
  inputs:
    version:
      type: "string"
      default: "16"
services:
  db:
    image: postgres:${version}
""",
        )
    )

    assert blueprint.id == "postgres"
    assert blueprint.display_name == "PostgreSQL"
    assert blueprint.category == "Databases"
    assert blueprint.inputs().model_json_schema()["title"] == "PostgreSQL"


def test_compose_blueprint_renders_services_ports_env_and_volumes(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
x-hosty:
  name: "PostgreSQL"
  ports: [db]
  secrets: [db_password]
  inputs:
    version:
      type: "string"
      default: "16"
    database:
      type: "string"
      default: "postgres"
    user:
      type: "string"
      default: "postgres"
services:
  db:
    image: postgres:${version:-16}
    ports:
      - 127.0.0.1:5432:5432/tcp
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${db_password:?generated by Hosty}
      POSTGRES_INITDB_ARGS: 123
    volumes:
      - db-data:/var/lib/postgresql/data
""",
        )
    )
    inputs = blueprint.inputs().model_validate({"version": "16", "database": "app", "user": "app"})
    spec = blueprint.render(
        "pg",
        inputs,
        Allocation(tenant="hosty-t-7", ports={"db": 20100}, secrets={"db_password": "secret"}),
    )

    assert spec.services[0].image == "postgres:16"
    assert spec.services[0].internal_port == 5432
    assert spec.services[0].host_port == 20100
    assert dict(spec.services[0].env) == {
        "POSTGRES_DB": "app",
        "POSTGRES_INITDB_ARGS": "123",
        "POSTGRES_PASSWORD": "secret",
        "POSTGRES_USER": "app",
    }
    assert spec.volumes[0].name == "db-data"
    assert spec.volumes[0].mount_path == "/var/lib/postgresql/data"


def test_compose_blueprint_rejects_missing_required_variable(tmp_path):
    blueprint = ComposeBlueprint(
        write_template(
            tmp_path,
            """
x-hosty:
  name: "Required"
services:
  app:
    image: ghcr.io/example/app:${missing:?}
""",
        )
    )

    with pytest.raises(SpecValidationError, match="missing"):
        blueprint.render(
            "app",
            blueprint.inputs().model_validate({}),
            Allocation(tenant="hosty-t-7", ports={}, secrets={}),
        )
