"""Blueprint #1: WordPress (v2/M5, ADR-013) — the v1 pipeline's parity
replacement, fully containerized.

Composition: `web` = official `wordpress:<php>-apache` image (digest-pinned
per supported PHP series) + `db` = per-stack MariaDB on the stack's internal
network (NO host port — only sibling containers can reach it). Private
`adminer` and `files` sidecars expose loopback-only ports for the panel's
existing ticket proxies; they are not public endpoints. Volumes: `html` (the
full /var/www/html so WP-CLI and Filebrowser can share it) + `db-data`.

WP-CLI runs as a transient `wordpress:cli` container (`podman run --rm`)
joined to the stack network and sharing the html volume + the web service's
env file — the same DB credentials and panel-managed salts the site sees.

Secrets: the DB password and a salt seed are panel-generated at create
(salts are derived from the seed so render stays pure); the admin password
is generated by the `install` action and returned show-once, never stored.

Day-2 actions reach v1 parity: install, core_update, plugins_update,
themes_update, maintenance_on/off, rotate_salts (env edit + restart via the
reconciler), admin_login_link (WordPress-native reset key, same TTL), and
status. `switch_php` is the blueprint-upgrade action: new web image, the
planner restarts the service.
"""

from __future__ import annotations

import hashlib
import json
import re
import secrets as pysecrets
from dataclasses import dataclass

import structlog
from pydantic import BaseModel, Field, field_validator
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.clock import utcnow
from app.core.config import Settings
from app.db.models import Stack, StackService, Tenant
from app.domain.specs import EndpointSpec, ServiceSpec, StackSpec, VolumeSpec
from app.orchestration.blueprints.base import (
    ActionHandler,
    ActionResult,
    Allocation,
    BackupHooks,
    StackHealth,
)
from app.system import podman, runner

log = structlog.get_logger("hosty.blueprint.wordpress")

WEB = "web"
DB = "db"
ADMINER = "adminer"
FILES = "files"
HTML_VOLUME = "html"
DB_VOLUME = "db-data"
DB_NAME = "wordpress"
DB_USER = "wordpress"
WWW_DATA = "33:33"  # www-data in the official images (inside the userns)

# Pinned per supported PHP series — a blueprint release updates these;
# existing stacks re-render only via the explicit switch_php upgrade action.
WEB_IMAGES = {
    "8.2": (
        "docker.io/library/wordpress:6.8-php8.2-apache"
        "@sha256:1e6215749283955d5c9ffea6c297651ed23cdfdbb91677ad7abd705b2682f2cf"
    ),
    "8.3": (
        "docker.io/library/wordpress:6.8-php8.3-apache"
        "@sha256:30bff39330d1693b0ce13d32fc9b7bb67193064f040b7d60d3494e136fa599d4"
    ),
    "8.4": (
        "docker.io/library/wordpress:6.8-php8.4-apache"
        "@sha256:da2a1ff20daa435abf260853ebfd829b1f5f9b8400938940c7393f786a63bf94"
    ),
}
CLI_IMAGE = (
    "docker.io/library/wordpress:cli-2.12"
    "@sha256:744d4cbfb63d6ed90808cf87d99f822ed569c9cec714f602ca7d2fc955892455"
)
DB_IMAGE = (
    "docker.io/library/mariadb:11.4"
    "@sha256:1b46b73d4b629022dfa29e6db3bb0d63b5df714fc3bfbe5057d63d76d8f6054b"
)
ADMINER_IMAGE = (
    "docker.io/library/adminer:5.3.0"
    "@sha256:2b845b0e8e89245afd5bce48c20f3348581021492a64667a2c38a8e7e1096c46"
)
FILEBROWSER_IMAGE = (
    "docker.io/filebrowser/filebrowser:v2.32.0"
    "@sha256:593478e3c24c5ea9f5d7478dc549965b7bc7030707291006ce8d0b6162d3454b"
)
DEFAULT_PHP = "8.3"

_PHP_FROM_IMAGE_RE = re.compile(r"php(\d+\.\d+)-apache")
LOCALE_RE = re.compile(r"^[a-z]{2,3}(_[A-Z]{2})?$")

# The 8 wp-config keys/salts, managed as env so the web AND cli containers
# agree, and so values survive container re-creation (random-per-start would
# log every user out on each restart).
SALT_ENV_KEYS = (
    "WORDPRESS_AUTH_KEY",
    "WORDPRESS_SECURE_AUTH_KEY",
    "WORDPRESS_LOGGED_IN_KEY",
    "WORDPRESS_NONCE_KEY",
    "WORDPRESS_AUTH_SALT",
    "WORDPRESS_SECURE_AUTH_SALT",
    "WORDPRESS_LOGGED_IN_SALT",
    "WORDPRESS_NONCE_SALT",
)


class WordPressActionError(RuntimeError):
    pass


class WordPressInputs(BaseModel):
    domain: str = Field(max_length=253, description="Public domain (HTTPS via Caddy)")
    title: str = Field(min_length=1, max_length=200, description="Site title")
    admin_user: str = Field(
        default="admin", min_length=3, max_length=60, pattern=r"^[a-zA-Z0-9_.\-@ ]+$"
    )
    admin_email: str = Field(max_length=254, pattern=r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
    locale: str = Field(default="en_US", description="WordPress locale, e.g. en_US, de_DE")
    php_version: str = Field(default=DEFAULT_PHP, description="PHP series")
    behind_cloudflare: bool = Field(
        default=False, description="Domain is proxied through Cloudflare"
    )
    memory_mb: int | None = Field(default=None, ge=64, le=1_048_576)

    @field_validator("locale")
    @classmethod
    def _locale(cls, v: str) -> str:
        if not LOCALE_RE.fullmatch(v):
            raise ValueError(f"Invalid locale: {v!r} (e.g. en_US, de_DE)")
        return v

    @field_validator("php_version")
    @classmethod
    def _php(cls, v: str) -> str:
        if v not in WEB_IMAGES:
            raise ValueError(f"Unsupported PHP version: {v!r} (one of {sorted(WEB_IMAGES)})")
        return v


def derive_salts(seed: str) -> dict[str, str]:
    """Deterministic full-entropy salts from one generated seed — render
    stays pure while each of the 8 keys gets a distinct value."""
    return {key: hashlib.sha256(f"{seed}:{key}".encode()).hexdigest() for key in SALT_ENV_KEYS}


def php_series_of(web_image: str) -> str:
    match = _PHP_FROM_IMAGE_RE.search(web_image)
    return match.group(1) if match else DEFAULT_PHP


# --- the execution context every action shares -------------------------------------


@dataclass(frozen=True)
class WpRuntime:
    """Everything needed to reach one stack's WordPress from the host."""

    uid: int
    tenant: str
    stack_name: str
    network: str
    html_dir: str
    env_file: str
    db_container: str


async def _runtime(db: AsyncSession, stack: Stack) -> WpRuntime:
    from app.system import quadlet

    if stack.owner_id is None:
        raise WordPressActionError("Stack has no owner; it is being torn down")
    tenant = f"hosty-t-{int(stack.owner_id)}"
    row = (
        await db.execute(select(Tenant).where(Tenant.user_id == stack.owner_id))
    ).scalar_one_or_none()
    if row is None or row.uid is None:
        raise WordPressActionError("Tenant is not provisioned yet — converge the stack first")
    return WpRuntime(
        uid=row.uid,
        tenant=tenant,
        stack_name=stack.name,
        network=f"hosty-{stack.name}",
        html_dir=quadlet.volume_host_dir(tenant, stack.name, HTML_VOLUME),
        env_file=quadlet.env_file_path(tenant, stack.name, WEB),
        db_container=f"{stack.name}-{DB}",
    )


async def run_wp(
    rt: WpRuntime, args: list[str], *, timeout: float = 120, check: bool = True
) -> runner.CommandResult:
    """One WP-CLI invocation: transient cli container in the stack network,
    sharing the html volume and the web env (DB credentials + salts)."""
    result = await podman.run_transient(
        rt.uid,
        CLI_IMAGE,
        ["wp", *args],
        network=rt.network,
        volumes=[(rt.html_dir, "/var/www/html")],
        env_file=rt.env_file,
        user=WWW_DATA,
        timeout=timeout,
    )
    if check and not result.ok:
        message = (result.stderr.strip() or result.stdout.strip())[:300]
        raise WordPressActionError(f"wp {args[0] if args else '?'} failed: {message}")
    return result


# --- actions ------------------------------------------------------------------------

# v1's login_link mechanism unchanged: WordPress's own reset key (native TTL),
# generated via `wp eval` — no extra packages, no network access.
_LOGIN_EVAL = (
    "$users = get_users(['role'=>'administrator','number'=>1,'fields'=>['ID','user_login']]);\n"
    "if(empty($users)){fwrite(STDERR,'No administrator found');exit(1);}\n"
    "$u=$users[0];\n"
    "$key=get_password_reset_key(get_userdata($u->ID));\n"
    "if(is_wp_error($key)){fwrite(STDERR,$key->get_error_message());exit(1);}\n"
    "echo network_site_url(\n"
    "  'wp-login.php?action=rp&key='.urlencode($key).'&login='.rawurlencode($u->user_login),\n"
    "  'login'\n"
    ");"
)


async def _is_installed(rt: WpRuntime) -> bool:
    return (await run_wp(rt, ["core", "is-installed"], timeout=60, check=False)).ok


def _bump_generation(stack: Stack) -> None:
    stack.generation += 1
    stack.status = "converging"
    stack.updated_at = utcnow()


async def _web_service(db: AsyncSession, stack: Stack) -> StackService:
    row = (
        await db.execute(
            select(StackService).where(StackService.stack_id == stack.id, StackService.name == WEB)
        )
    ).scalar_one_or_none()
    if row is None:
        raise WordPressActionError("Stack has no web service")
    return row


class WordPressBlueprint:
    id = "wordpress"
    version = 1
    category = "Applications"
    icon = "wordpress"
    display_name = "WordPress"
    description = "Deploy a fully containerized WordPress instance with MariaDB, Adminer, and Filebrowser."

    def inputs(self) -> type[WordPressInputs]:
        return WordPressInputs

    def ports_needed(self, inputs: WordPressInputs) -> list[str]:
        return [WEB, ADMINER, FILES]

    def secrets_needed(self, inputs: WordPressInputs) -> list[str]:
        return ["db_password", "salt_seed"]

    def render(self, name: str, inputs: WordPressInputs, alloc: Allocation) -> StackSpec:
        db_password = alloc.secrets["db_password"]
        web_env = {
            "WORDPRESS_DB_HOST": f"{name}-{DB}",
            "WORDPRESS_DB_NAME": DB_NAME,
            "WORDPRESS_DB_USER": DB_USER,
            "WORDPRESS_DB_PASSWORD": db_password,
            **derive_salts(alloc.secrets["salt_seed"]),
        }
        web = ServiceSpec(
            name=WEB,
            image=WEB_IMAGES[inputs.php_version],
            env=tuple(sorted(web_env.items())),
            internal_port=80,
            host_port=alloc.ports[WEB],
            memory_mb=inputs.memory_mb,
            is_web=True,
        )
        database = ServiceSpec(
            name=DB,
            image=DB_IMAGE,
            env=tuple(
                sorted(
                    {
                        "MARIADB_DATABASE": DB_NAME,
                        "MARIADB_USER": DB_USER,
                        "MARIADB_PASSWORD": db_password,
                        "MARIADB_RANDOM_ROOT_PASSWORD": "1",
                    }.items()
                )
            ),
        )
        adminer = ServiceSpec(
            name=ADMINER,
            image=ADMINER_IMAGE,
            env=(("ADMINER_DEFAULT_SERVER", f"{name}-{DB}"),),
            internal_port=8080,
            host_port=alloc.ports[ADMINER],
        )
        files = ServiceSpec(
            name=FILES,
            image=FILEBROWSER_IMAGE,
            env=tuple(
                sorted(
                    {
                        "FB_BASEURL": "/files",
                        "FB_NOAUTH": "true",
                        "FB_ROOT": "/srv",
                    }.items()
                )
            ),
            internal_port=80,
            host_port=alloc.ports[FILES],
        )
        return StackSpec(
            name=name,
            tenant=alloc.tenant,
            services=(web, database, adminer, files),
            volumes=(
                VolumeSpec(name=HTML_VOLUME, service=WEB, mount_path="/var/www/html"),
                VolumeSpec(name=HTML_VOLUME, service=FILES, mount_path="/srv"),
                VolumeSpec(name=DB_VOLUME, service=DB, mount_path="/var/lib/mysql"),
            ),
            endpoints=(
                EndpointSpec(
                    domain=inputs.domain,
                    service=WEB,
                    behind_cloudflare=inputs.behind_cloudflare,
                ),
            ),
        )

    # --- day-2 ----------------------------------------------------------------------

    def actions(self) -> dict[str, ActionHandler]:
        return {
            "install": self._install,
            "core_update": self._core_update,
            "plugins_update": self._plugins_update,
            "themes_update": self._themes_update,
            "maintenance_on": self._maintenance_on,
            "maintenance_off": self._maintenance_off,
            "rotate_salts": self._rotate_salts,
            "admin_login_link": self._admin_login_link,
            "status": self._status,
            "switch_php": self._switch_php,
        }

    async def _install(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        rt = await _runtime(db, stack)
        if await _is_installed(rt):
            return ActionResult(ok=False, message="WordPress is already installed")
        parsed = WordPressInputs.model_validate(inputs)
        admin_password = pysecrets.token_urlsafe(18)
        await run_wp(
            rt,
            [
                "core",
                "install",
                f"--url=https://{parsed.domain}",
                f"--title={parsed.title}",
                f"--admin_user={parsed.admin_user}",
                f"--admin_password={admin_password}",
                f"--admin_email={parsed.admin_email}",
                "--skip-email",
            ],
            timeout=300,
        )
        if parsed.locale != "en_US":
            # Locale is best-effort: a failed language download must not fail
            # the install (the site is up in en_US; retry via WP admin).
            result = await run_wp(
                rt,
                ["language", "core", "install", parsed.locale, "--activate"],
                timeout=300,
                check=False,
            )
            if not result.ok:
                log.warning("wp_locale_install_failed", stack=stack.name, locale=parsed.locale)
        return ActionResult(
            ok=True,
            message=f"WordPress installed at https://{parsed.domain}",
            show_once={"admin_password": admin_password},
        )

    async def _core_update(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        rt = await _runtime(db, stack)
        await run_wp(rt, ["core", "update"], timeout=300)
        await run_wp(rt, ["core", "update-db"], timeout=120)
        return ActionResult(ok=True, message="WordPress core updated")

    async def _plugins_update(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        rt = await _runtime(db, stack)
        await run_wp(rt, ["plugin", "update", "--all"], timeout=600)
        return ActionResult(ok=True, message="Plugins updated")

    async def _themes_update(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        rt = await _runtime(db, stack)
        await run_wp(rt, ["theme", "update", "--all"], timeout=600)
        return ActionResult(ok=True, message="Themes updated")

    async def _maintenance_on(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        rt = await _runtime(db, stack)
        await run_wp(rt, ["maintenance-mode", "activate"])
        return ActionResult(ok=True, message="Maintenance mode on")

    async def _maintenance_off(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        rt = await _runtime(db, stack)
        await run_wp(rt, ["maintenance-mode", "deactivate"])
        return ActionResult(ok=True, message="Maintenance mode off")

    async def _rotate_salts(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        """New salts = edit the web service's desired env + let the
        reconciler rewrite the unit and restart — no host I/O here."""
        from app.services.stacks import decrypt_env, encrypt_env

        web = await _web_service(db, stack)
        env = decrypt_env(web, settings)
        env.update(derive_salts(pysecrets.token_urlsafe(32)))
        web.env_encrypted = encrypt_env(env, settings)
        _bump_generation(stack)
        await db.commit()
        return ActionResult(
            ok=True,
            message="Salts rotated — the web service is restarting; all sessions are logged out",
        )

    async def _admin_login_link(
        self, *, db, settings, stack: Stack, inputs, params
    ) -> ActionResult:
        rt = await _runtime(db, stack)
        result = await run_wp(rt, ["eval", _LOGIN_EVAL])
        url = result.stdout.strip()
        if not url:
            raise WordPressActionError("admin_login_link: wp eval returned an empty URL")
        return ActionResult(
            ok=True,
            message="One-time login link created (WordPress reset-key TTL applies)",
            show_once={"login_url": url},
        )

    async def _status(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        rt = await _runtime(db, stack)
        if not await _is_installed(rt):
            return ActionResult(ok=True, data={"installed": False})

        async def out(args: list[str], timeout: float = 60) -> str | None:
            result = await run_wp(rt, args, timeout=timeout, check=False)
            return result.stdout.strip() if result.ok else None

        version = await out(["core", "version"])
        update_available = None
        updates_json = await out(["core", "check-update", "--format=json"])
        if updates_json:
            try:
                updates = json.loads(updates_json)
                if updates:
                    update_available = updates[0].get("version")
            except (json.JSONDecodeError, AttributeError, IndexError):
                update_available = None

        def count(raw: str | None) -> int | None:
            return int(raw) if raw is not None and raw.isdigit() else None

        return ActionResult(
            ok=True,
            data={
                "installed": True,
                "version": version,
                "update_available": update_available,
                "plugin_updates": count(
                    await out(["plugin", "list", "--update=available", "--format=count"])
                ),
                "theme_updates": count(
                    await out(["theme", "list", "--update=available", "--format=count"])
                ),
            },
        )

    async def _switch_php(self, *, db, settings, stack: Stack, inputs, params) -> ActionResult:
        """The blueprint-upgrade action: re-pin the web image; the planner
        sees a new spec hash and restarts the service."""
        from app.services.stacks import decrypt_inputs, encrypt_inputs

        target = params.get("php_version") if isinstance(params, dict) else None
        if target not in WEB_IMAGES:
            return ActionResult(
                ok=False,
                message=f"Unsupported PHP version: {target!r} (one of {sorted(WEB_IMAGES)})",
            )
        web = await _web_service(db, stack)
        if php_series_of(web.image) == target:
            return ActionResult(ok=True, message=f"Already on PHP {target}")
        web.image = WEB_IMAGES[target]
        web.image_digest = None  # re-resolved against the new tag
        stored = decrypt_inputs(stack, settings)
        stored["php_version"] = target
        stack.inputs_encrypted = encrypt_inputs(stored, settings)
        _bump_generation(stack)
        await db.commit()
        return ActionResult(
            ok=True, message=f"Switching to PHP {target} — the web service is restarting"
        )

    # --- backups (wired in M5 backup ops) ---------------------------------------------

    def backup_hooks(self) -> BackupHooks:
        return BackupHooks(
            pre_backup=self._pre_backup,
            post_restore=self._post_restore,
            databases=(DB_NAME,),
        )

    async def _pre_backup(self, *, db, settings: Settings, stack: Stack, directory) -> None:
        """Consistent SQL dump via the db container, streamed to the staging
        dir (never through memory). Credentials travel as env, not argv."""
        from app.services.stacks import decrypt_env

        rt = await _runtime(db, stack)
        password = decrypt_env(await _db_service(db, stack), settings).get("MARIADB_PASSWORD")
        if not password:
            raise WordPressActionError("No database password in the stack's desired state")
        dest = str(directory / f"{DB_NAME}.sql")
        result = await podman.exec_in(
            rt.uid,
            rt.db_container,
            ["mariadb-dump", "--single-transaction", "--quick", f"--user={DB_USER}", DB_NAME],
            env={"MYSQL_PWD": password},
            timeout=600,
            stdout_path=dest,
        )
        if not result.ok:
            raise WordPressActionError(f"mariadb-dump failed: {result.stderr.strip()[:300]}")

    async def _post_restore(self, *, db, settings: Settings, stack: Stack, directory) -> None:
        """Re-import the dump after volumes are restored and the db service
        is running again (the caller guarantees ordering)."""
        from app.services.stacks import decrypt_env

        rt = await _runtime(db, stack)
        password = decrypt_env(await _db_service(db, stack), settings).get("MARIADB_PASSWORD")
        if not password:
            raise WordPressActionError("No database password in the stack's desired state")
        dump = directory / f"{DB_NAME}.sql"
        if not dump.is_file():
            return  # backup made before install — volumes only
        result = await podman.exec_in(
            rt.uid,
            rt.db_container,
            ["mariadb", f"--user={DB_USER}", DB_NAME],
            env={"MYSQL_PWD": password},
            timeout=600,
            stdin_path=str(dump),
        )
        if not result.ok:
            raise WordPressActionError(f"database import failed: {result.stderr.strip()[:300]}")

    def health(self, observed_active: dict[str, bool]) -> StackHealth:
        missing = [s for s in (WEB, DB) if not observed_active.get(s)]
        if not missing:
            return StackHealth(healthy=True)
        return StackHealth(healthy=False, detail=f"not running: {', '.join(missing)}")


async def _db_service(db: AsyncSession, stack: Stack) -> StackService:
    row = (
        await db.execute(
            select(StackService).where(StackService.stack_id == stack.id, StackService.name == DB)
        )
    ).scalar_one_or_none()
    if row is None:
        raise WordPressActionError("Stack has no db service")
    return row
