"""Quadlet unit rendering + placement paths (v2/M2, ADR-013). PURE text
builders — no I/O lives here; the executor (M3) writes the rendered files
through the fs seam.

Inputs are domain specs, which are validated at construction — a StackSpec
that exists cannot inject into unit text (the grammar rejects newlines, NULs
and `:` in mount components). Hardening lines are emitted ALWAYS, not
optionally: NoNewPrivileges, loopback-only PublishPort, journald logging,
`hosty.*` labels.

Env values never enter unit text: each service gets an EnvironmentFile
(0600, tenant-owned, content from `env_file_text`).

Placement: root-managed per-user units in `/etc/containers/systemd/users/
<uid>/` (podman ≥ 4.9, Ubuntu 24.04). The `# hosty-spec-hash=` marker is
the convergence fingerprint observers read back (domain `spec_hash`).
"""

from __future__ import annotations

import re

from app.domain.specs import ServiceSpec, StackSpec, spec_hash
from app.system.tenants import home_dir_for, validate_tenant_username

MANAGED_HEADER = "# hosty-managed — generated by the panel; manual edits are overwritten"
SPEC_HASH_MARKER = "# hosty-spec-hash="
_SPEC_HASH_RE = re.compile(r"^# hosty-spec-hash=([a-f0-9]{32})$", re.MULTILINE)
# Ownership markers: filenames are ambiguous (both stack and service slugs
# may contain hyphens), so sync and observe attribute files by CONTENT.
_STACK_MARKER_RE = re.compile(r"^# hosty-stack=([a-z0-9-]{1,32})$", re.MULTILINE)
_SERVICE_MARKER_RE = re.compile(r"^# hosty-service=([a-z0-9-]{1,32})$", re.MULTILINE)


def unit_dir(uid: int) -> str:
    """Root-managed quadlet directory for one tenant's user manager."""
    if not isinstance(uid, int) or isinstance(uid, bool) or uid <= 0:
        raise ValueError(f"Invalid uid: {uid!r}")
    return f"/etc/containers/systemd/users/{uid}"


def stacks_root(tenant: str) -> str:
    return f"{home_dir_for(validate_tenant_username(tenant))}/stacks"


def stack_dir(tenant: str, stack: str) -> str:
    return f"{stacks_root(tenant)}/{stack}"


def volume_host_dir(tenant: str, stack: str, volume: str) -> str:
    return f"{stack_dir(tenant, stack)}/volumes/{volume}"


def env_file_path(tenant: str, stack: str, service: str) -> str:
    return f"{stack_dir(tenant, stack)}/env/{service}.env"


def container_file_name(stack: str, service: str) -> str:
    return f"{stack}-{service}.container"


def build_file_name(stack: str, service: str) -> str:
    return f"{stack}-{service}.build"


def network_file_name(stack: str) -> str:
    return f"{stack}.network"


def service_unit_name(stack: str, service: str) -> str:
    """The systemd unit quadlet generates from `<stack>-<service>.container`."""
    return f"{stack}-{service}.service"


def env_file_text(service: ServiceSpec) -> str:
    """EnvironmentFile content. Values are grammar-checked at spec
    construction (no newline/NUL), so each pair is exactly one line."""
    return "".join(f"{key}={value}\n" for key, value in service.env)





def container_unit(stack: StackSpec, service: ServiceSpec) -> str:
    image = build_file_name(stack.name, service.name) if service.build_repo else service.image
    lines = [
        MANAGED_HEADER,
        f"# hosty-stack={stack.name}",
        f"# hosty-service={service.name}",
        f"{SPEC_HASH_MARKER}{spec_hash(stack, service)}",
        "",
        "[Unit]",
        f"Description=hosty stack {stack.name} — service {service.name}",
        "",
        "[Container]",
        f"ContainerName={stack.name}-{service.name}",
        f"Image={image}",
        f"Network={network_file_name(stack.name)}",
        # Hardening — unconditional.
        "NoNewPrivileges=true",
        "LogDriver=journald",
        f"Label=hosty.stack={stack.name}",
        "Label=hosty.managed=1",
    ]
    if service.internal_port is not None:
        # Loopback ONLY: a bare publish would bypass the host firewall.
        lines.append(f"PublishPort=127.0.0.1:{service.host_port}:{service.internal_port}")
    if service.env:
        lines.append(f"EnvironmentFile={env_file_path(stack.tenant, stack.name, service.name)}")
    for volume in stack.volumes_for(service.name):
        host_dir = volume_host_dir(stack.tenant, stack.name, volume.name)
        lines.append(f"Volume={host_dir}:{volume.mount_path}")
    podman_args: list[str] = []
    if service.memory_mb is not None:
        podman_args.append(f"--memory={int(service.memory_mb)}m")
    if service.cpu_percent is not None:
        podman_args.append(f"--cpus={int(service.cpu_percent) / 100:g}")
    if podman_args:
        lines.append(f"PodmanArgs={' '.join(podman_args)}")
    lines += [
        "",
        "[Service]",
        "Restart=always",
        # Image pulls on first start can be slow; do not let systemd give up.
        "TimeoutStartSec=300",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ]
    return "\n".join(lines)


def network_unit(stack: StackSpec) -> str:
    return "\n".join(
        [
            MANAGED_HEADER,
            f"# hosty-stack={stack.name}",
            "",
            "[Network]",
            f"NetworkName={stack.network}",
            f"Label=hosty.stack={stack.name}",
            "Label=hosty.managed=1",
            "",
        ]
    )


def build_unit(stack: StackSpec, service: ServiceSpec) -> str:
    branch = f"#{service.build_branch}" if service.build_branch else ""
    return "\n".join(
        [
            MANAGED_HEADER,
            f"# hosty-stack={stack.name}",
            f"# hosty-service={service.name}",
            f"{SPEC_HASH_MARKER}{spec_hash(stack, service)}",
            "",
            "[Build]",
            f"ImageTag=hosty/{stack.name}-{service.name}:latest",
            f"SetWorkingDirectory={service.build_repo}{branch}",
            "",
        ]
    )


def unit_files(stack: StackSpec) -> dict[str, str]:
    """The COMPLETE desired unit-file set for a stack: what WriteUnits syncs
    the quadlet directory to (write these, delete any other file of this
    stack)."""
    files = {network_file_name(stack.name): network_unit(stack)}
    for service in stack.services:
        files[container_file_name(stack.name, service.name)] = container_unit(stack, service)
        if service.build_repo:
            files[build_file_name(stack.name, service.name)] = build_unit(stack, service)
    return files


def env_files(stack: StackSpec) -> dict[str, str]:
    """Path -> content for every service that needs an EnvironmentFile."""
    return {
        env_file_path(stack.tenant, stack.name, service.name): env_file_text(service)
        for service in stack.services
        if service.env
    }


def read_spec_hash(unit_text: str) -> str | None:
    """Total: returns the embedded fingerprint, or None for foreign/corrupt
    files (which the planner therefore always treats as stale)."""
    if not isinstance(unit_text, str):
        return None
    match = _SPEC_HASH_RE.search(unit_text)
    return match.group(1) if match else None


def read_stack_marker(unit_text: str) -> str | None:
    """Total: which stack owns this unit file, by content marker."""
    if not isinstance(unit_text, str):
        return None
    match = _STACK_MARKER_RE.search(unit_text)
    return match.group(1) if match else None


def read_service_marker(unit_text: str) -> str | None:
    """Total: which service a `.container` file renders, by content marker."""
    if not isinstance(unit_text, str):
        return None
    match = _SERVICE_MARKER_RE.search(unit_text)
    return match.group(1) if match else None
