"""Quadlet unit rendering + placement paths (v2/M2, ADR-013). PURE text
builders — no I/O lives here; the executor (M3) writes the rendered files
through the fs seam.

Inputs are domain specs, which are validated at construction — a StackSpec
that exists cannot inject into unit text (the grammar rejects newlines, NULs
and `:` in mount components). Hardening lines are emitted ALWAYS, not
optionally: NoNewPrivileges, loopback-only PublishPort, journald logging,
`hosty.*` labels.

Env values never enter unit text: each service gets an EnvironmentFile
(0600, tenant-owned, content from `env_file_text`).

Placement: root-managed per-user units in `/etc/containers/systemd/users/
<uid>/` (podman ≥ 4.6). The `# hosty-spec-hash=` marker is
the convergence fingerprint observers read back (domain `spec_hash`).
"""

from __future__ import annotations

import re

from app.domain.specs import ServiceSpec, StackSpec, spec_hash, derive_host_port
from app.system.tenants import home_dir_for, validate_tenant_username

MANAGED_HEADER = "# hosty-managed — generated by the panel; manual edits are overwritten"
SPEC_HASH_MARKER = "# hosty-spec-hash="
_SPEC_HASH_RE = re.compile(r"^# hosty-spec-hash=([a-f0-9]{32})$", re.MULTILINE)
# Ownership markers: filenames are ambiguous (both stack and service slugs
# may contain hyphens), so sync and observe attribute files by CONTENT.
_STACK_MARKER_RE = re.compile(r"^# hosty-stack=([a-z0-9-]{1,32})$", re.MULTILINE)
_SERVICE_MARKER_RE = re.compile(r"^# hosty-service=([a-z0-9-]{1,32})$", re.MULTILINE)


def unit_dir(uid: int) -> str:
    """Root-managed quadlet directory for one tenant's user manager."""
    if not isinstance(uid, int) or isinstance(uid, bool) or uid <= 0:
        raise ValueError(f"Invalid uid: {uid!r}")
    return f"/etc/containers/systemd/users/{uid}"


def stacks_root(tenant: str) -> str:
    return f"{home_dir_for(validate_tenant_username(tenant))}/stacks"


def stack_dir(tenant: str, stack: str) -> str:
    return f"{stacks_root(tenant)}/{stack}"


def volume_host_dir(tenant: str, stack: str, volume: str) -> str:
    return f"{stack_dir(tenant, stack)}/volumes/{volume}"


def env_file_path(tenant: str, stack: str, service: str) -> str:
    return f"{stack_dir(tenant, stack)}/env/{service}.env"


def container_file_name(stack: str, service: str) -> str:
    return f"{stack}-{service}.container"


def build_file_name(stack: str, service: str) -> str:
    return f"{stack}-{service}.build"


def network_file_name(stack: str) -> str:
    return f"{stack}.network"


def service_unit_name(stack: str, service: str) -> str:
    """The systemd unit quadlet generates from `<stack>-<service>.container`."""
    return f"{stack}-{service}.service"


def env_file_text(service: ServiceSpec) -> str:
    """EnvironmentFile content. Values are grammar-checked at spec
    construction (no newline/NUL), so each pair is exactly one line."""
    return "".join(f"{key}={value}\n" for key, value in service.env)


def _volume_owner_counts(stack: StackSpec) -> dict[str, int]:
    """volume name -> how many services in the stack mount it."""
    counts: dict[str, int] = {}
    for volume in stack.volumes:
        counts[volume.name] = counts.get(volume.name, 0) + 1
    return counts


def container_unit(stack: StackSpec, service: ServiceSpec) -> str:
    if service.build_repo:
        if service.build_tool == "nixpacks":
            image = f"hosty/{stack.name}-{service.name}:latest"
        else:
            image = build_file_name(stack.name, service.name)
    else:
        image = service.image
    lines = [
        MANAGED_HEADER,
        f"# hosty-stack={stack.name}",
        f"# hosty-service={service.name}",
        f"{SPEC_HASH_MARKER}{spec_hash(stack, service)}",
        "",
        "[Unit]",
        f"Description=hosty stack {stack.name} — service {service.name}",
    ]
    
    if service.build_repo and service.build_tool == "nixpacks":
        lines.extend([
            f"Requires={stack.name}-{service.name}-nixpacks.service",
            f"After={stack.name}-{service.name}-nixpacks.service",
        ])
    # depends_on ordering: start dependencies first. Combined with Restart=always,
    # this handles service_healthy semantics — the dependent container restarts
    # until the dependency is up and accepting connections.
    for dep in service.depends_on:
        dep_unit = f"{stack.name}-{dep}.service"
        lines.extend([
            f"Requires={dep_unit}",
            f"After={dep_unit}",
        ])
        
    lines.extend([
        "",
        "[Container]",
        f"ContainerName={stack.name}-{service.name}",
        f"Image={image}",
        f"Network={network_file_name(stack.name)}",
        # Hardening — unconditional.
        "NoNewPrivileges=true",
        "LogDriver=journald",
        f"Label=hosty.stack={stack.name}",
        "Label=hosty.managed=1",
    ])
    if service.internal_port is not None:
        # Loopback IP derived from stack ID by default. An explicitly EXPOSED
        # service binds 0.0.0.0 so it is reachable on the server's public IP.
        bind = "0.0.0.0" if service.exposed else stack.loopback_ip
        host_port = derive_host_port(service.internal_port)
        lines.append(f"PublishPort={bind}:{host_port}:{service.internal_port}")
    if service.command:
        lines.append(f"Exec={' '.join(service.command)}")
    if service.env:
        lines.append(f"EnvironmentFile={env_file_path(stack.tenant, stack.name, service.name)}")
    # A volume mounted by exactly one service across the stack gets `:U` so
    # podman chowns its host dir to the UID the container runs as: rootless
    # images that drop privileges (postgres→999, mariadb→999, …) cannot write
    # a tenant-owned bind mount otherwise, and crash on first start. SHARED
    # volumes (e.g. WordPress `html` mounted by both `web` and `files`) are
    # left alone — `:U` would thrash ownership between the two containers.
    exclusive = {name for name, count in _volume_owner_counts(stack).items() if count == 1}
    for volume in stack.volumes_for(service.name):
        host_dir = volume_host_dir(stack.tenant, stack.name, volume.name)
        suffix = ":U" if volume.name in exclusive else ""
        lines.append(f"Volume={host_dir}:{volume.mount_path}{suffix}")
    # Always register a network alias equal to the compose service name so
    # other containers in the stack can resolve it by short name (e.g.
    # "postgres" instead of "mattermost-abc-postgres").  Using PodmanArgs
    # rather than the Quadlet NetworkAlias= key because NetworkAlias= was
    # added in Podman 4.7 while PodmanArgs= works with all Podman >= 4.4.
    podman_args: list[str] = [f"--network-alias={service.name}"]
    if service.memory_mb is not None:
        podman_args.append(f"--memory={int(service.memory_mb)}m")
    if service.cpu_percent is not None:
        podman_args.append(f"--cpus={int(service.cpu_percent) / 100:g}")
    lines.append(f"PodmanArgs={' '.join(podman_args)}")
    lines += [
        "",
        "[Service]",
        "Restart=always",
        # Image pulls on first start can be slow; do not let systemd give up.
        "TimeoutStartSec=300",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ]
    return "\n".join(lines)


def network_unit(stack: StackSpec) -> str:
    return "\n".join(
        [
            MANAGED_HEADER,
            f"# hosty-stack={stack.name}",
            "",
            "[Network]",
            f"NetworkName={stack.network}",
            f"Label=hosty.stack={stack.name}",
            "Label=hosty.managed=1",
            "",
        ]
    )


def build_unit(stack: StackSpec, service: ServiceSpec) -> str:
    workspace = f"%h/stacks/{stack.name}/src"
    return "\n".join(
        [
            MANAGED_HEADER,
            f"# hosty-stack={stack.name}",
            f"# hosty-service={service.name}",
            f"{SPEC_HASH_MARKER}{spec_hash(stack, service)}",
            "",
            "[Unit]",
            f"After={stack.name}-git-sync.service",
            f"Requires={stack.name}-git-sync.service",
            "",
            "[Build]",
            f"ImageTag=hosty/{stack.name}-{service.name}:latest",
            f"SetWorkingDirectory={workspace}",
            "",
        ]
    )


def nixpacks_build_unit(stack: StackSpec, service: ServiceSpec) -> str:
    workspace = f"%h/stacks/{stack.name}/src"
    image_tag = f"hosty/{stack.name}-{service.name}:latest"
    return "\n".join(
        [
            MANAGED_HEADER,
            f"# hosty-stack={stack.name}",
            f"# hosty-service={service.name}",
            f"{SPEC_HASH_MARKER}{spec_hash(stack, service)}",
            "",
            "[Unit]",
            f"Description=hosty Nixpacks build {stack.name} — service {service.name}",
            f"After={stack.name}-git-sync.service",
            f"Requires={stack.name}-git-sync.service",
            "",
            "[Service]",
            "Type=oneshot",
            f"WorkingDirectory={workspace}",
            f"ExecStart=/usr/bin/env nixpacks build . --name {image_tag}",
            "TimeoutStartSec=1800",
            "",
            "[Install]",
            "WantedBy=default.target",
        ]
    )


def unit_files(stack: StackSpec, git_clone_url: str | None = None) -> dict[str, str]:
    """The COMPLETE desired unit-file set for a stack: what WriteUnits syncs
    the quadlet directory to (write these, delete any other file of this
    stack).

    `git_clone_url` is an optional authenticated override for the git-sync
    clone command (e.g. with a GitHub App installation token injected).
    """
    from app.system.git_sync import git_sync_unit

    files = {network_file_name(stack.name): network_unit(stack)}
    needs_git_sync = False

    for service in stack.services:
        files[container_file_name(stack.name, service.name)] = container_unit(stack, service)
        if service.build_repo:
            if service.build_tool == "nixpacks":
                files[f"{stack.name}-{service.name}-nixpacks.service"] = nixpacks_build_unit(stack, service)
            else:
                files[build_file_name(stack.name, service.name)] = build_unit(stack, service)
            needs_git_sync = True

    if needs_git_sync:
        files[f"{stack.name}-git-sync.service"] = git_sync_unit(stack, clone_url=git_clone_url)

    return files


def env_files(stack: StackSpec) -> dict[str, str]:
    """Path -> content for every service that needs an EnvironmentFile."""
    return {
        env_file_path(stack.tenant, stack.name, service.name): env_file_text(service)
        for service in stack.services
        if service.env
    }


def read_spec_hash(unit_text: str) -> str | None:
    """Total: returns the embedded fingerprint, or None for foreign/corrupt
    files (which the planner therefore always treats as stale)."""
    if not isinstance(unit_text, str):
        return None
    match = _SPEC_HASH_RE.search(unit_text)
    return match.group(1) if match else None


def read_stack_marker(unit_text: str) -> str | None:
    """Total: which stack owns this unit file, by content marker."""
    if not isinstance(unit_text, str):
        return None
    match = _STACK_MARKER_RE.search(unit_text)
    return match.group(1) if match else None


def read_service_marker(unit_text: str) -> str | None:
    """Total: which service a `.container` file renders, by content marker."""
    if not isinstance(unit_text, str):
        return None
    match = _SERVICE_MARKER_RE.search(unit_text)
    return match.group(1) if match else None
