"""remove stack_services.host_port

Revision ID: 42d5b7cdddef
Revises: 0019
Create Date: 2026-06-13 20:42:44.250663
"""
from alembic import op
import sqlalchemy as sa


revision = '42d5b7cdddef'
down_revision = '0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stack_services', 'host_port')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_services', sa.Column('host_port', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
