"""add_post_start_command_to_stack_services

Revision ID: 6175be6e3b5d
Revises: 0028_stack_build_config
Create Date: 2026-06-15 03:46:51.442529

MIGRATION SAFETY RULES — read before editing:
  • create_index  → always pass  if_not_exists=True
  • drop_index    → always pass  if_exists=True
  • create_table  → always pass  if_not_exists=True
  • add_column    → wrap in try/except OperationalError for SQLite,
                    or check column existence first for Postgres
  • alter_column  → use batch_alter_table for SQLite compatibility
These guards make migrations idempotent so a partial run or a DB that
already has the object (e.g. from create_tables_on_startup) never
breaks the deploy.
"""
from alembic import op
import sqlalchemy as sa


revision = '6175be6e3b5d'
down_revision = '0028_stack_build_config'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_services', sa.Column('post_start_command', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stack_services', 'post_start_command')
    # ### end Alembic commands ###
