"""shared_variables_global

Revision ID: a50f8c72bb62
Revises: 6776efaa5d6e
Create Date: 2026-06-14 04:44:12.519814
"""
from alembic import op
import sqlalchemy as sa


revision = 'a50f8c72bb62'
down_revision = '6776efaa5d6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_variables')
    # ### end Alembic commands ###
