"""add_health_check_and_watch_paths

Revision ID: e6560c0babcc
Revises: 6175be6e3b5d
Create Date: 2026-06-15 04:07:07.338741

MIGRATION SAFETY RULES — read before editing:
  • create_index  → always pass  if_not_exists=True
  • drop_index    → always pass  if_exists=True
  • create_table  → always pass  if_not_exists=True
  • add_column    → wrap in try/except OperationalError for SQLite,
                    or check column existence first for Postgres
  • alter_column  → use batch_alter_table for SQLite compatibility
These guards make migrations idempotent so a partial run or a DB that
already has the object (e.g. from create_tables_on_startup) never
breaks the deploy.
"""
from alembic import op
import sqlalchemy as sa


revision = 'e6560c0babcc'
down_revision = '6175be6e3b5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack_services', sa.Column('health_check_enabled', sa.Boolean(), nullable=False))
    op.add_column('stack_services', sa.Column('health_check_path', sa.String(length=255), nullable=True))
    op.add_column('stack_services', sa.Column('health_check_port', sa.Integer(), nullable=True))
    op.add_column('stack_services', sa.Column('health_check_interval', sa.Integer(), nullable=False))
    op.add_column('stack_services', sa.Column('health_check_retries', sa.Integer(), nullable=False))
    op.add_column('stack_services', sa.Column('health_check_start_period', sa.Integer(), nullable=False))
    op.add_column('stack_services', sa.Column('health_check_timeout', sa.Integer(), nullable=False))
    op.add_column('stacks', sa.Column('watch_paths_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stacks', 'watch_paths_json')
    op.drop_column('stack_services', 'health_check_timeout')
    op.drop_column('stack_services', 'health_check_start_period')
    op.drop_column('stack_services', 'health_check_retries')
    op.drop_column('stack_services', 'health_check_interval')
    op.drop_column('stack_services', 'health_check_port')
    op.drop_column('stack_services', 'health_check_path')
    op.drop_column('stack_services', 'health_check_enabled')
    # ### end Alembic commands ###
