"""Add GitSource model

Revision ID: e677454aa443
Revises: 42d5b7cdddef
Create Date: 2026-06-13 23:43:06.991332
"""
from alembic import op
import sqlalchemy as sa


revision = 'e677454aa443'
down_revision = '42d5b7cdddef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('private_key_encrypted', sa.Text(), nullable=False),
    sa.Column('webhook_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_git_sources_owner_name')
    )
    op.create_index(op.f('ix_git_sources_owner_id'), 'git_sources', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_sources_owner_id'), table_name='git_sources')
    op.drop_table('git_sources')
    # ### end Alembic commands ###
