x-hosty:
  name: "Adminer"
  version: 1
  category: "Developer Tools"
  icon: "database"
  description: "Deploy Adminer for browser-based database administration."
  web: web
  ports:
    - web

services:
  web:
    image: docker.io/library/adminer:4@sha256:ee94dcfafed929cdd6e0bc25e74ce1bf92b71e5c9a7e94e9fee5e3993e7d49dd
    ports:
      - 8080:8080
