x-hosty:
  name: "Bitcoin Core"
  version: 1
  category: "Applications"
  icon: "box"
  description: "A self-hosted Bitcoin Core full node."
  secrets:
    - password64_password

services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:latest
    environment:
      - BITCOIN_RPCUSER=${BITCOIN_RPCUSER:-bitcoinuser}
      - BITCOIN_RPCPASSWORD=${password64_password}
      - BITCOIN_PRINTTOCONSOLE=${BITCOIN_PRINTTOCONSOLE:-1}
      - BITCOIN_TXINDEX=${BITCOIN_TXINDEX:-1}
      - BITCOIN_SERVER=${BITCOIN_SERVER:-1}
    volumes:
      - blockchain-data:/home/bitcoin/.bitcoin
    command:
      [
        "-datadir=/home/bitcoin/.bitcoin",
        "-rpcbind=127.0.0.1", # only allow local connections
        "-rpcallowip=127.0.0.1",
        "-rpcuser=${BITCOIN_RPCUSER}",
        "-rpcpassword=${password64_password}",
        "-printtoconsole=${BITCOIN_PRINTTOCONSOLE}",
        "-txindex=${BITCOIN_TXINDEX}",
        "-server=${BITCOIN_SERVER}"
      ]
