x-hosty:
  name: "Code Server"
  version: 1
  category: "Developer Tools"
  icon: "code-2"
  description: "Code-Server is a web-based code editor that enables remote coding and collaboration from any device, anywhere."
  web: code-server
  secrets:
    - passwordcodeserver_key
    - sudocodeserver_password

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    environment:

    - PUID=1000
    - PGID=1000
    - TZ=Europe/Madrid
    - PASSWORD=${passwordcodeserver_key}
    - SUDO_PASSWORD=${sudocodeserver_password}
    - DEFAULT_WORKSPACE=/config/workspace
    volumes:
    - code-server-config:/config
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:8443
      interval: 2s
      timeout: 10s
      retries: 15
    ports:
    - 8443:8443
