x-hosty:
  name: "Ghost"
  version: 1
  category: "Applications"
  icon: "file-text"
  description: "Ghost is a powerful app for new-media creators to publish, share, and grow a business around their content."
  ports:
    - web
  secrets:
    - db_password
  inputs:
    domain:
      type: "string"
      description: "Public domain (e.g. https://myblog.com)"

services:
  db:
    image: docker.io/library/mysql:8.0@sha256:7dcddc01f13bab2f15cde676d44d01f61fc9f99fe7785e86196dfc07d358ae2b
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${db_password}
    volumes:
      - db-data:/var/lib/mysql

  web:
    image: docker.io/library/ghost:5@sha256:3ffcb8f2f1f808806e7a0f694a2b130cd78652a26b4337b33fe7e249ce58665a
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ${db_password}
      database__connection__database: ghost
      url: ${domain}
    volumes:
      - ghost-content:/var/lib/ghost/content
