x-hosty:
  name: "Glances"
  version: 1
  category: "Monitoring"
  icon: "activity"
  description: "An Eye on your system"
  web: glances

services:
  glances:
    image: nicolargo/glances:latest
    restart: unless-stopped
    environment:
    - GLANCES_OPT=-w

    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    pid: host
    privileged: true
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:61208
      interval: 2s
      timeout: 10s
      retries: 30
    ports:
    - 61208:61208
