x-hosty:
  name: "Gowa"
  version: 1
  category: "Applications"
  icon: "box"
  description: "Golang WhatsApp - Built with Go for efficient memory use"
  web: gowa
  secrets:
    - gowa_password
  inputs:
    gowa_user:
      type: "string"
      default: "gowa"
      description: "Gowa username"

services:
  gowa:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    environment:

    - SERVICE_USER_GOWA
    - SERVICE_PASSWORD_GOWA
    - APP_BASIC_AUTH=${gowa_user}:${gowa_password}
    - APP_PORT=3000
    - APP_DEBUG=${APP_DEBUG:-false}
    - APP_ACCOUNT_VALIDATION=${APP_ACCOUNT_VALIDATION:-false}
    - WHATSAPP_WEBHOOK=${WHATSAPP_WEBHOOK}
    - WHATSAPP_WEBHOOK_SECRET=${WHATSAPP_WEBHOOK_SECRET}
    volumes:
    - gowa_data:/app/storages
    ports:
    - 3000:3000
