x-hosty:
  name: "Grafana"
  version: 1
  category: "Monitoring"
  icon: "bar-chart-3"
  description: "Deploy Grafana dashboards and visualization."
  web: web
  ports:
    - web

services:
  web:
    image: docker.io/grafana/grafana:11.5.2
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
