x-hosty:
  name: "Hoppscotch"
  version: 1
  category: "Developer Tools"
  icon: "code-2"
  description: "The Open Source API Development Platform"
  web: backend
  domain_input: domain
  secrets:
    - postgres_password
  inputs:
    postgres_user:
      type: "string"
      default: "postgres"
      description: "Postgres username"
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"

services:
  backend:
    image: hoppscotch/hoppscotch:2026.2.1
    environment:

    - VITE_ALLOWED_AUTH_PROVIDERS=${VITE_ALLOWED_AUTH_PROVIDERS:-GOOGLE,GITHUB,MICROSOFT,EMAIL}
    - DATABASE_URL=postgresql://${postgres_user}:${postgres_password}@hoppscotch-db:5432/${POSTGRES_DB}
    - DATA_ENCRYPTION_KEY=${SERVICE_BASE64_DATAENCRYPTIONKEY}
    - WHITELISTED_ORIGINS=${domain}/backend,${domain},${domain}/admin
    - MAILER_USE_CUSTOM_CONFIGS=${MAILER_USE_CUSTOM_CONFIGS:-true}
    - VITE_BASE_URL=${domain}
    - VITE_SHORTCODE_BASE_URL=${domain}
    - VITE_ADMIN_URL=${domain}/admin
    - VITE_BACKEND_GQL_URL=${domain}/backend/graphql
    - VITE_BACKEND_WS_URL=wss://${domain}/backend/graphql
    - VITE_BACKEND_API_URL=${domain}/backend/v1
    - VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
    - VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy
    - ENABLE_SUBPATH_BASED_ACCESS=true
    depends_on:
      db-migration:
        condition: service_completed_successfully
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1:80/
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
    - 80:80
  hoppscotch-db:
    image: postgres:15
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=${postgres_user}
    - POSTGRES_PASSWORD=${postgres_password}
    - POSTGRES_DB=${POSTGRES_DB:-hoppscotch}
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 10s
      retries: 10
  db-migration:
    exclude_from_hc: true
    image: hoppscotch/hoppscotch:2026.2.1
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    command: pnpx prisma migrate deploy
    restart: on-failure
    environment:
    - POSTGRES_USER=${postgres_user}
    - POSTGRES_PASSWORD=${postgres_password}
    - POSTGRES_DB=${POSTGRES_DB:-hoppscotch}
    - DATABASE_URL=postgres://${postgres_user}:${postgres_password}@hoppscotch-db:5432/${POSTGRES_DB:-hoppscotch}
