x-hosty:
  name: "Jellyfin"
  version: 1
  category: "Media"
  icon: "film"
  description: "Jellyfin is a media server for hosting and streaming your media collection."
  web: jellyfin
  domain_input: domain
  inputs:
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.8
    environment:

    - PUID=1000
    - PGID=1000
    - TZ=Europe/Madrid
    - JELLYFIN_PublishedServerUrl=${domain}
    volumes:
    - jellyfin-config:/config
    - jellyfin-tvshows:/data/tvshows
    - jellyfin-movies:/data/movies
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:8096
      interval: 2s
      timeout: 10s
      retries: 15
    ports:
    - 8096:8096
