x-hosty:
  name: "Labelstudio"
  version: 1
  category: "AI"
  icon: "brain-circuit"
  description: "Label Studio is a multi-type data labeling and annotation tool with standardized output format"
  web: labelstudio
  domain_input: domain
  secrets:
    - postgres_password
    - labelstudio_password
  inputs:
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"
    postgres_user:
      type: "string"
      default: "postgres"
      description: "Postgres username"

services:
  labelstudio:
    image: heartexlabs/label-studio:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:

    - CSRF_TRUSTED_ORIGINS=${domain}
    - EXPERIMENTAL_FEATURES=${EXPERIMENTAL_FEATURES:-false}
    - DJANGO_DB=${DJANGO_DB:-default}
    - POSTGRE_NAME=${POSTGRES_DB:-labelstudio}
    - POSTGRE_USER=${postgres_user}
    - POSTGRE_PASSWORD=${postgres_password}
    - POSTGRE_PORT=5432
    - POSTGRE_HOST=postgres
    - LABEL_STUDIO_HOST=${domain}
    - SSRF_PROTECTION_ENABLED=${SSRF_PROTECTION_ENABLED:-true}
    - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=${LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK:-true}
    - DATA_UPLOAD_MAX_NUMBER_FILES=${DATA_UPLOAD_MAX_NUMBER_FILES:-10000}
    - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME:-admin@example.com}
    - LABEL_STUDIO_PASSWORD=${labelstudio_password}
    - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=${LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK:-true}
    volumes:
    - labelstudio-data:/label-studio/data
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 20s
      retries: 3
    ports:
    - 8080:8080
  postgres:
    image: postgres:16-alpine
    environment:
    - POSTGRES_USER=${postgres_user}
    - POSTGRES_PASSWORD=${postgres_password}
    - POSTGRES_DB=${POSTGRES_DB:-labelstudio}
    volumes:
    - pg-data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 20s
      retries: 3
