x-hosty:
  name: "Libreoffice"
  version: 1
  category: "Applications"
  icon: "box"
  description: "LibreOffice is a free and powerful office suite."
  web: libreoffice

services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    environment:

    - PUID=${PUID:-1000}
    - PGID=${PGID:-1000}
    - TZ=${TZ:-Etc/UTC}
    volumes:
    - libreoffice-config:/config
    healthcheck:
      test:
      - CMD
      - wget
      - -q
      - --spider
      - http://localhost:3000
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
    - 3000:3000
