x-hosty:
  name: "Mage AI"
  version: 1
  category: "Automation"
  icon: "zap"
  description: "Build, run, and manage data pipelines for integrating and transforming data."
  web: mage-ai

services:
  mage-ai:
    image: mageai/mageai:0.9.78
    command: mage start default_project
    environment:

    - PROJECT_NAME=default_project
    - USER_CODE_PATH=/home/src/default_project
    - ENV=production
    volumes:
    - mageai_data:/home/src/
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -s
      - -f
      - -o
      - /dev/null
      - http://127.0.0.1:6789
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
    - 6789:6789
