x-hosty:
  name: "MariaDB"
  version: 1
  category: "Databases"
  icon: "mariadb"
  description: "MariaDB is a community-developed, commercially supported fork of the MySQL relational database management system."
  ports:
    - db
  secrets:
    - root_password
    - db_password
  inputs:
    database:
      type: "string"
      default: "mariadb"
      description: "Default database name"
    user:
      type: "string"
      default: "mariadb"
      description: "User name"

services:
  db:
    image: docker.io/library/mariadb:11.4@sha256:1b46b73d4b629022dfa29e6db3bb0d63b5df714fc3bfbe5057d63d76d8f6054b
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${root_password}
      MARIADB_DATABASE: ${database}
      MARIADB_USER: ${user}
      MARIADB_PASSWORD: ${db_password}
    volumes:
      - db-data:/var/lib/mysql
