x-hosty:
  name: "Meilisearch"
  version: 1
  category: "Search"
  icon: "search"
  description: "MeiliSearch is a powerful, fast, easy to use and deploy search engine."
  web: meilisearch
  secrets:
    - meilisearch_password

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:

    - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
    - MEILI_ENV=${MEILI_ENV:-production}
    - MEILI_MASTER_KEY=${meilisearch_password}
    volumes:
    - meilisearch-data:/meili_data
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:7700/health
      interval: 2s
      timeout: 10s
      retries: 15
    ports:
    - 7700:7700
