x-hosty:
  name: "Metabase"
  version: 1
  category: "Analytics"
  icon: "bar-chart-2"
  description: "Fast analytics with the friendly UX and integrated tooling to let your company explore data on their own."
  web: metabase
  secrets:
    - postgresql_password
  inputs:
    postgresql_user:
      type: "string"
      default: "postgresql"
      description: "Postgresql username"

services:
  metabase:
    image: metabase/metabase:latest
    volumes:
    - /dev/urandom:/dev/random:ro
    environment:

    - MB_DB_TYPE=postgres
    - MB_DB_HOST=postgresql
    - MB_DB_PORT=5432
    - MB_DB_DBNAME=${POSTGRESQL_DATABASE:-metabase}
    - MB_DB_USER=${postgresql_user}
    - MB_DB_PASS=${postgresql_password}
    healthcheck:
      test: curl --fail -I http://127.0.0.1:3000/api/health || exit 1
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
    - 3000:3000
  postgresql:
    image: postgres:16-alpine
    volumes:
    - metabase-postgresql-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=${postgresql_user}
    - POSTGRES_PASSWORD=${postgresql_password}
    - POSTGRES_DB=${POSTGRESQL_DATABASE:-metabase}
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 20s
      retries: 10
