x-hosty:
  name: "Mosquitto"
  version: 1
  category: "Applications"
  icon: "box"
  description: "Mosquitto is lightweight and suitable for use on all devices, from low-power single-board computers to full servers."
  web: mosquitto
  secrets:
    - mosquitto_password
  inputs:
    mosquitto_user:
      type: "string"
      default: "mosquitto"
      description: "Mosquitto username"

services:
  mosquitto:
    image: eclipse-mosquitto
    environment:

      - MQTT_USERNAME=${mosquitto_user}
      - MQTT_PASSWORD=${mosquitto_password}
      - REQUIRE_CERTIFICATE=${REQUIRE_CERTIFICATE:-false}
      - ALLOW_ANONYMOUS=${ALLOW_ANONYMOUS:-true}
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./certs:/certs"
    ports:
      - "8883:8883"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: 'sh -c "
      if [ ''$REQUIRE_CERTIFICATE'' = ''true'' ]; then
      echo ''listener 8883'' > /mosquitto/config/mosquitto.conf &&
      echo ''cafile /certs/ca.crt'' >> /mosquitto/config/mosquitto.conf &&
      echo ''certfile /certs/server.crt'' >> /mosquitto/config/mosquitto.conf &&
      echo ''keyfile  /certs/server.key'' >> /mosquitto/config/mosquitto.conf;
      else
      echo ''listener 1883'' > /mosquitto/config/mosquitto.conf;
      fi &&
      echo ''require_certificate ''$REQUIRE_CERTIFICATE >> /mosquitto/config/mosquitto.conf &&
      echo ''allow_anonymous ''$ALLOW_ANONYMOUS >> /mosquitto/config/mosquitto.conf;
      if [ -n ''${mosquitto_user}'' ] && [ -n ''${mosquitto_password}'' ]; then
      echo ''password_file /mosquitto/config/passwords'' >> /mosquitto/config/mosquitto.conf &&
      touch /mosquitto/config/passwords &&
      chmod 0700 /mosquitto/config/passwords &&
      chown root:root /mosquitto/config/passwords &&
      mosquitto_passwd -b -c /mosquitto/config/passwords ${mosquitto_user} ${mosquitto_password} &&
      chown mosquitto:mosquitto /mosquitto/config/passwords;
      fi &&
      exec mosquitto -c /mosquitto/config/mosquitto.conf
      "'
    labels:
      - traefik.tcp.routers.mqtt.entrypoints=mqtt
      - traefik.tcp.routers.mqtts.entrypoints=mqtts
