x-hosty:
  name: "Nginx"
  version: 1
  category: "Web Servers"
  icon: "server"
  description: "Deploy a lightweight Nginx web server."
  web: web
  ports:
    - web

services:
  web:
    image: docker.io/library/nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10
    ports:
      - 80:80
    volumes:
      - html:/usr/share/nginx/html
