x-hosty:
  name: "Nginx"
  version: 1
  category: "Web Servers"
  icon: "server"
  description: "Deploy a lightweight Nginx web server."
  web: web
  ports:
    - web

services:
  web:
    image: docker.io/library/nginx:1.27-alpine
    ports:
      - 80:80
    volumes:
      - html:/usr/share/nginx/html
