x-hosty:
  name: "NocoDB"
  version: 1
  category: "Databases"
  icon: "database"
  description: "NocoDB is an open source #NoCode platform that turns any database into a smart spreadsheet."
  ports:
    - web
  secrets:
    - db_password
    - jwt_secret
services:
  db:
    image: docker.io/library/postgres:15@sha256:c2ca90969ca293925ab474466e837689cc712321afdd9e4640bd0cf942fdca3a
    environment:
      POSTGRES_DB: nocodb
      POSTGRES_USER: nocodb
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    image: docker.io/nocodb/nocodb:latest@sha256:46f325fc066e36ccfb80c41608cd8661e86d2610ad4567fda06eac2209235fcf
    ports:
      - 8080:8080
    environment:
      NC_DB: "pg://db:5432?u=nocodb&p=${db_password}&d=nocodb"
      NC_AUTH_JWT_SECRET: ${jwt_secret}
    volumes:
      - nc-data:/usr/app/data/
