x-hosty:
  name: "Pgadmin"
  version: 1
  category: "Databases"
  icon: "database"
  description: "pgAdmin is a web-based database management tool for administering your PostgreSQL databases through a user-friendly interface."

services:
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:

      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:?}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:?}'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/login"]
      interval: 5s
      timeout: 10s
      retries: 5
