x-hosty:
  name: "phpMyAdmin"
  version: 1
  category: "Developer Tools"
  icon: "database"
  description: "Deploy phpMyAdmin with arbitrary MySQL or MariaDB server login."
  web: web
  ports:
    - web

services:
  web:
    image: docker.io/library/phpmyadmin:5
    ports:
      - 80:80
    environment:
      PMA_ARBITRARY: "1"
