x-hosty:
  name: "PostgreSQL"
  version: 1
  category: "Databases"
  icon: "postgres"
  description: "Deploy a PostgreSQL database."
  ports:
    - db
  secrets:
    - db_password
  inputs:
    database:
      type: "string"
      default: "postgres"
      description: "Default database name"
    user:
      type: "string"
      default: "postgres"
      description: "Superuser name"

services:
  db:
    image: docker.io/library/postgres:16@sha256:081f1bc7bd5e143dbb6e487b710bbc27712cdcfaced4c071b8e47349aa1b4171
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - db-data:/var/lib/postgresql/data
