x-hosty:
  name: "Privatebin"
  version: 1
  category: "Security"
  icon: "shield"
  description: "PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data."
  web: privatebin

services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    environment:

    volumes:
    - privatebin_data:/srv/data
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1:8080/
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
    - 8080:8080
