x-hosty:
  name: "Prometheus"
  version: 1
  category: "Monitoring"
  icon: "activity"
  description: "Deploy Prometheus for metrics collection and querying."
  web: web
  ports:
    - web

services:
  web:
    image: docker.io/prom/prometheus:v3.1.0
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
