x-hosty:
  name: "Rabbitmq"
  version: 1
  category: "Applications"
  icon: "box"
  description: "With tens of thousands of users, RabbitMQ is one of the most popular open source message brokers."
  web: rabbitmq
  secrets:
    - rabbitmq_password
  inputs:
    rabbitmq_user:
      type: "string"
      default: "rabbitmq"
      description: "Rabbitmq username"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    environment:

      - RABBITMQ_DEFAULT_USER=${rabbitmq_user}
      - RABBITMQ_DEFAULT_PASS=${rabbitmq_password}
      - PORT=${PORT:-5672}
    ports:
      - ${PORT}:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 10
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
