x-hosty:
  name: "Redis"
  version: 1
  category: "Databases"
  icon: "redis"
  description: "Redis is an open source, in-memory data structure store, used as a database, cache, and message broker."
  ports:
    - db
  secrets:
    - password
services:
  db:
    image: docker.io/library/redis:7.2@sha256:747f1f4078d700806f83d427550a9d8c4d89dd3bf6491449c748c83ad285036e
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${password}
    volumes:
      - db-data:/data
