x-hosty:
  name: "Seafile"
  version: 1
  category: "Storage"
  icon: "hard-drive"
  description: "Open source cloud storage system for file sync, share and document collaboration"
  web: seafile
  domain_input: domain
  secrets:
    - mysqlroot_password
    - mysql_password
    - admin_password
    - jwt_key
  inputs:
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"
    mysql_user:
      type: "string"
      default: "mysql"
      description: "Mysql username"

services:
  seafile:
    image: seafileltd/seafile-mc:12.0-latest
    volumes:
    - seafile-data:/shared
    environment:

    - SEAFILE_SERVER_HOSTNAME=${domain}
    - DB_HOST=mariadb
    - DB_PORT=3306
    - DB_ROOT_PASSWD=${mysqlroot_password}
    - DB_USER=${mysql_user}
    - DB_PASSWORD=${mysql_password}
    - SEAFILE_MYSQL_DB_CCNET_DB_NAME=${SEAFILE_MYSQL_DB_CCNET_DB_NAME:-ccnet_db}
    - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=${SEAFILE_MYSQL_DB_SEAFILE_DB_NAME:-seafile_db}
    - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=${SEAFILE_MYSQL_DB_SEAHUB_DB_NAME:-seahub_db}
    - TIME_ZONE=${TIME_ZONE:-UTC}
    - INIT_SEAFILE_ADMIN_EMAIL=${INIT_SEAFILE_ADMIN_EMAIL:-test@example.com}
    - INIT_SEAFILE_ADMIN_PASSWORD=${admin_password}
    - SEAFILE_SERVER_PROTOCOL=https
    - SITE_ROOT=${SITE_ROOT:-/}
    - NON_ROOT=${NON_ROOT:-false}
    - JWT_PRIVATE_KEY=${jwt_key}
    - SEAFILE_LOG_TO_STDOUT=${SEAFILE_LOG_TO_STDOUT:-true}
    - FILE_SERVER_ROOT=${domain}/seafhttp
    depends_on:
      mariadb:
        condition: service_healthy
      memcached:
        condition: service_started
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:80/api2/ping
      interval: 10s
      timeout: 20s
      retries: 5
    ports:
    - 80:80
  mariadb:
    image: mariadb:11
    volumes:
    - seafile_mariadb_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${mysqlroot_password}
    - MYSQL_USER=${mysql_user}
    - MYSQL_PASSWORD=${mysql_password}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-seafile-db}
    healthcheck:
      test:
      - CMD
      - healthcheck.sh
      - --connect
      - --innodb_initialized
      interval: 10s
      timeout: 20s
      retries: 5
  memcached:
    image: memcached:latest
    entrypoint: memcached -m 256
    healthcheck:
      test:
      - CMD-SHELL
      - bash -c "echo version | (exec 3<>/dev/tcp/localhost/11211; cat >&3; timeout
        0.5 cat <&3; exec 3<&-)"
      interval: 10s
      timeout: 20s
      retries: 5
