x-hosty:
  name: "Sonarr"
  version: 1
  category: "Media"
  icon: "film"
  description: "Sonarr⁠ (formerly NZBdrone) is a PVR for usenet and bittorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be c..."
  web: sonarr
  domain_input: domain
  inputs:
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:

    - _APP_URL=${domain}
    - PUID=1000
    - PGID=1000
    - TZ=${TZ:-America/Toronto}
    volumes:
    - sonarr-config:/config
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8989/ping
      interval: 2s
      timeout: 10s
      retries: 15
    ports:
    - 8989:8989
