x-hosty:
  name: "Sparkyfitness"
  version: 1
  category: "Applications"
  icon: "box"
  description: "SparkyFitness is a comprehensive fitness tracking and management application designed to help users monitor their nutrition, exercise, and body measurements. It provides tools for daily progress tr..."
  web: sparkyfitness-frontend
  domain_input: domain
  secrets:
    - postgres_password
    - serverapiencryptionkey_key
    - serverjwtsecret_key
  inputs:
    postgres_user:
      type: "string"
      default: "postgres"
      description: "Postgres username"
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"

services:
  sparkyfitness-frontend:
    image: codewithcj/sparkyfitness:v0.15.7.3
    environment:

    depends_on:
    - sparkyfitness-server
    ports:
    - 80:80
  sparkyfitness-server:
    image: codewithcj/sparkyfitness_server:v0.15.7.3
    environment:
    - SPARKY_FITNESS_LOG_LEVEL=${SPARKY_FITNESS_LOG_LEVEL:-info}
    - SPARKY_FITNESS_DB_USER=${postgres_user}
    - SPARKY_FITNESS_DB_HOST=sparkyfitness-db
    - SPARKY_FITNESS_DB_NAME=${SPARKY_FITNESS_DB_NAME:-sparkyfitness}
    - SPARKY_FITNESS_DB_PASSWORD=${postgres_password}
    - SPARKY_FITNESS_DB_PORT=${SPARKY_FITNESS_DB_PORT:-5432}
    - SPARKY_FITNESS_API_ENCRYPTION_KEY=${serverapiencryptionkey_key}
    - JWT_SECRET=${serverjwtsecret_key}
    - SPARKY_FITNESS_FRONTEND_URL=${domain}_80}
    - SPARKY_FITNESS_DISABLE_SIGNUP=${SPARKY_FITNESS_DISABLE_SIGNUP:-false}
    - SPARKY_FITNESS_ADMIN_EMAIL=${SPARKY_FITNESS_ADMIN_EMAIL:-admin@example.com}
    - SPARKY_FITNESS_EMAIL_HOST=${SPARKY_FITNESS_EMAIL_HOST:-smtp.gmail.com}
    - SPARKY_FITNESS_EMAIL_PORT=${SPARKY_FITNESS_EMAIL_PORT:-587}
    - SPARKY_FITNESS_EMAIL_SECURE=${SPARKY_FITNESS_EMAIL_SECURE:-false}
    - SPARKY_FITNESS_EMAIL_USER=${SPARKY_FITNESS_EMAIL_USER}
    - SPARKY_FITNESS_EMAIL_PASS=${SPARKY_FITNESS_EMAIL_PASS}
    - SPARKY_FITNESS_EMAIL_FROM=${SPARKY_FITNESS_EMAIL_FROM:-"Sparky Fitness <noreply@sparkyfitness.com>"}
    depends_on:
    - sparkyfitness-db
    volumes:
    - sparkyfitness-server-backup:/app/SparkyFitnessServer/backup
    - sparkyfitness-server-uploads:/app/SparkyFitnessServer/uploads
  sparkyfitness-db:
    image: postgres:15-alpine
    environment:
    - POSTGRES_DB=${SPARKY_FITNESS_DB_NAME:-sparkyfitness}
    - POSTGRES_USER=${postgres_user}
    - POSTGRES_PASSWORD=${postgres_password}
    - POSTGRES_PORT=${SPARKY_FITNESS_DB_PORT:-5432}
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
    - sparkyfitness-db-postgresql:/var/lib/postgresql/data
