x-hosty:
  name: "Supertokens With Postgresql"
  version: 1
  category: "Security"
  icon: "shield"
  description: "An open-source authentication solution that simplifies the implementation of secure user authentication and session management for web and mobile applications."
  web: supertokens
  secrets:
    - postgresql_password
  inputs:
    postgresql_user:
      type: "string"
      default: "postgresql"
      description: "Postgresql username"

services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:

    - API_KEYS=${API_KEYS:-}
    - POSTGRESQL_CONNECTION_URI="postgresql://${postgresql_user}:${postgresql_password}@postgres:5432/${POSTGRES_DB:-supertokens}"
    healthcheck:
      test: 'bash -c ''exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost:
        127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"''

        '
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 3567:3567
  postgres:
    image: postgres:16
    environment:
    - POSTGRES_USER=${postgresql_user}
    - POSTGRES_PASSWORD=${postgresql_password}
    - POSTGRES_DB=${POSTGRES_DB:-supertokens}
    volumes:
    - supertokens-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - ${postgresql_user}
      - -d
      - ${POSTGRES_DB:-supertokens}
      interval: 5s
      timeout: 5s
      retries: 5
