x-hosty:
  name: "Teable"
  version: 1
  category: "Applications"
  icon: "box"
  description: "Teable is a powerful visual interface built on relational databases (PostgreSQL)."
  web: teable
  domain_input: domain
  secrets:
    - postgres_password
    - secret_key
    - redis_password
  inputs:
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"
    postgres_user:
      type: "string"
      default: "postgres"
      description: "Postgres username"

services:
  teable:
    image: ghcr.io/teableio/teable:latest
    volumes:
    - teable_data:/app/.assets:rw
    environment:

    - PUBLIC_ORIGIN=${domain}
    - POSTGRES_PASSWORD=${postgres_password}
    - SECRET_KEY=${secret_key}
    - TZ=${TIMEZONE}
    - PRISMA_DATABASE_URL=postgresql://${postgres_user}:${postgres_password}@teable-db:${POSTGRES_PORT}/${POSTGRES_DB}
    - NEXT_ENV_IMAGES_ALL_REMOTE=true
    - PORT=3000
    - REDIS_PASSWORD=${redis_password}
    - BACKEND_CACHE_PROVIDER=redis
    - BACKEND_CACHE_REDIS_URI=redis://default:${redis_password}@teable-cache:6379/0
    - BACKEND_MAIL_HOST=${BACKEND_MAIL_HOST}
    - BACKEND_MAIL_PORT=${BACKEND_MAIL_PORT}
    - BACKEND_MAIL_SECURE=${BACKEND_MAIL_SECURE}
    - BACKEND_MAIL_SENDER=${BACKEND_MAIL_SENDER}
    - BACKEND_MAIL_SENDER_NAME=${BACKEND_MAIL_SENDER_NAME}
    - BACKEND_MAIL_AUTH_USER=${BACKEND_MAIL_AUTH_USER}
    - BACKEND_MAIL_AUTH_PASS=${BACKEND_MAIL_AUTH_PASS}
    depends_on:
      teable-cache:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:3000
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
    - 3000:3000
  teable-db:
    image: postgres:15.4
    volumes:
    - teable_db_data:/var/lib/postgresql/data:rw
    environment:
    - TZ=${TIMEZONE}
    - POSTGRES_DB=${POSTGRES_DB:-teable}
    - POSTGRES_PASSWORD=${postgres_password}
    - POSTGRES_USER=${postgres_user}
    - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 20s
      retries: 10
  teable-db-migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    restart: false
    environment:
    - TZ=${TIMEZONE}
    - PRISMA_DATABASE_URL=postgresql://${postgres_user}:${postgres_password}@teable-db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      teable-db:
        condition: service_healthy
  teable-cache:
    image: redis:7.2.4
    environment:
    - REDIS_PORT=6379
    - REDIS_DB=0
    - REDIS_PASSWORD=${redis_password}
    volumes:
    - teable_cache_data:/data:rw
    command: redis-server --appendonly yes --requirepass ${redis_password}
    healthcheck:
      test:
      - CMD
      - redis-cli
      - --raw
      - incr
      - ping
      interval: 10s
      timeout: 3s
      retries: 3
