x-hosty:
  name: "Umami"
  version: 1
  category: "Analytics"
  icon: "bar-chart-2"
  description: "Umami is web analytics platform which provides insights into visitor behavior without compromising user privacy."
  web: umami
  secrets:
    - postgres_password
    - umami_key
  inputs:
    postgres_user:
      type: "string"
      default: "postgres"
      description: "Postgres username"

services:
  umami:
    image: ghcr.io/umami-software/umami:3.0.3
    environment:

    - DATABASE_URL=postgres://${postgres_user}:${postgres_password}@postgresql:5432/$POSTGRES_DB
    - DATABASE_TYPE=postgres
    - APP_SECRET=${umami_key}
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:3000/api/heartbeat
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
    - 3000:3000
  postgresql:
    image: postgres:16-alpine
    volumes:
    - postgresql-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=${postgres_user}
    - POSTGRES_PASSWORD=${postgres_password}
    - POSTGRES_DB=${POSTGRES_DB:-umami}
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 20s
      retries: 10
