x-hosty:
  name: "Uptime Kuma"
  version: 1
  category: "Monitoring"
  icon: "activity"
  description: "Uptime Kuma is a monitoring tool for tracking the status and performance of your applications in real-time."
  web: uptime-kuma

services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:2
    environment:

    volumes:
    - uptime-kuma-data:/app/data
    healthcheck:
      test:
      - CMD-SHELL
      - extra/healthcheck
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
    - 3001:3001
