x-hosty:
  name: "Uptime Kuma With Mariadb"
  version: 1
  category: "Monitoring"
  icon: "activity"
  description: "Uptime Kuma is a monitoring tool for tracking the status and performance of your applications in real-time."
  web: uptime-kuma
  secrets:
    - mariadb_password
    - root_password
  inputs:
    mariadb_user:
      type: "string"
      default: "mariadb"
      description: "Mariadb username"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    environment:

    - TZ=${TZ:-Etc/UTC}
    volumes:
    - uptime-kuma-data:/app/data
    healthcheck:
      test:
      - CMD-SHELL
      - extra/healthcheck
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
    - 3001:3001
  mariadb:
    image: mariadb:11
    environment:
    - MYSQL_USER=${mariadb_user}
    - MYSQL_PASSWORD=${mariadb_password}
    - MYSQL_ROOT_PASSWORD=${root_password}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-uptime-kuma-db}
    healthcheck:
      test:
      - CMD
      - healthcheck.sh
      - --connect
      - --innodb_initialized
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
    - mariadb-data:/var/lib/mysql
