x-hosty:
  name: "Vikunja With Postgresql"
  version: 1
  category: "Applications"
  icon: "box"
  description: "The open-source, self-hostable to-do app. Organize everything, on all platforms."
  secrets:
    - jwtsecret_password
    - postgresql_password
  inputs:
    domain:
      type: "string"
      description: "Public domain (e.g. https://app.example.com)"
    postgresql_user:
      type: "string"
      default: "postgresql"
      description: "Postgresql username"

services:
  vikunja:
    image: vikunja/vikunja
    environment:

      - VIKUNJA_SERVICE_PUBLICURL=${domain}
      - VIKUNJA_SERVICE_JWTSECRET=${jwtsecret_password}
      - VIKUNJA_SERVICE_ENABLEREGISTRATION=true
      - VIKUNJA_DATABASE_TYPE=postgres
      - VIKUNJA_DATABASE_HOST=postgresql
      - VIKUNJA_DATABASE_PASSWORD=${postgresql_password}
      - VIKUNJA_DATABASE_USER=${postgresql_user}
      - VIKUNJA_DATABASE_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - vikunja-data:/app/vikunja/
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: postgres:16-alpine
    volumes:
      - vikunja-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${postgresql_user}
      - POSTGRES_PASSWORD=${postgresql_password}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10
