x-hosty:
  name: "Vvveb With Mariadb"
  version: 1
  category: "CMS"
  icon: "file-text"
  description: "Powerful and easy to use cms to build websites, blogs or ecommerce stores."
  web: vvveb
  secrets:
    - vvveb_password
    - root_password
  inputs:
    vvveb_user:
      type: "string"
      default: "vvveb"
      description: "Vvveb username"

services:
  vvveb:
    image: vvveb/vvvebcms:latest
    volumes:
    - vvveb-data:/var/www/html
    environment:

    - DB_ENGINE=mysqli
    - DB_HOST=mariadb
    - DB_USER=${vvveb_user}
    - DB_PASSWORD=${vvveb_password}
    - DB_NAME=${MARIADB_DATABASE:-vvveb}
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1
      interval: 2s
      timeout: 10s
      retries: 10
    ports:
    - 80:80
  mariadb:
    image: mariadb:11
    volumes:
    - vvveb-mariadb-data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${root_password}
    - MYSQL_DATABASE=${MARIADB_DATABASE:-vvveb}
    - MYSQL_USER=${vvveb_user}
    - MYSQL_PASSWORD=${vvveb_password}
    healthcheck:
      test:
      - CMD
      - healthcheck.sh
      - --connect
      - --innodb_initialized
      interval: 5s
      timeout: 20s
      retries: 10
