x-hosty:
  name: "Web Check"
  version: 1
  category: "Monitoring"
  icon: "activity"
  description: "All-in-one OSINT tool for analysing any website"
  web: web-check

services:
  web-check:
    image: lissy93/web-check
    environment:

    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1:3000/
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
    - 3000:3000
